---
- name: Install Docker
  hosts: app
  become: true
  tasks:
    - name: Add Docker GPG key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

    - name: Install list of packages
      apt:
        name: ['apt-transport-https','ca-certificates','curl','software-properties-common','docker-ce', 'python3-pip','docker-compose']
        state: present
        update_cache: yes

    - name: Install ansible module for docker
      pip:
        name: docker
        executable: pip3
